name: EDML Schema Workflow Generation

on:
  push:
    branches:
      - 'master'

jobs:
  main:
    name: schema-generation
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Edml Schema
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Maven settings configuration
        run: envsubst < .github/settings.template.xml > settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Schema Validation
        uses: divloic/ccloud-registry-action@v0.0.1
        with:
          schema-registry-url: ${{ secrets.SCHEMA_REGISTRY_URL }}
          schema-registry-api-key: ${{ secrets.SCHEMA_REGISTRY_API_KEY }}
          schema-registry-secret-key: ${{ secrets.SCHEMA_REGISTRY_SECRET_KEY }}

      - name: Maven Code Generation
        run: ./mvnw -B avrohugger:generate-scala-sources

      - name: Maven Deploy Jar Archive
        run: ./mvnw -B -s settings.xml deploy